[font]
size = 13.0

# [font.bold]
# family = "PlemolJP35 Console NF"
# style = "Bold"

# [font.bold_italic]
# family = "PlemolJP35 Console NF"
# style = "Bold Italic"

# [font.italic]
# family = "PlemolJP35 Console NF"
# style = "Italic"

# [font.normal]
# family = "PlemolJP35 Console NF"
# style = "Regular"
[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[env]
TERM = "xterm-256color"

# Colors (Iceberg)
# Default colors
[colors.primary]
background = '#161821'
foreground = '#c6c8d1'

[colors.cursor]
text = '#161821'
cursor = '#c6c8d1'

# Normal colors
[colors.normal]
black   = '#1e2132'
red     = '#e27878'
green   = '#b4be82'
yellow  = '#e2a478'
blue    = '#84a0c6'
magenta = '#a093c7'
cyan    = '#89b8c2'
white   = '#c6c8d1'

# Bright colors
[colors.bright]
black   = '#6b7089'
red     = '#e98989'
green   = '#c0ca8e'
yellow  = '#e9b189'
blue    = '#91acd1'
magenta = '#ada0d3'
cyan    = '#95c4ce'
white   = '#d2d4de'

[keyboard]
bindings = [
  { key   = "ArrowUp", mods  = "Control|Alt", action = "ToggleMaximized" },
]
