#!/usr/bin/env zsh

export EDITOR=vim
export MYDOTFILES=$HOME/dotfiles

function chpwd() {ls}
if [[ ! -n $TMUX ]]; then
	tmux attach || tmux new-session
else
	if [[ `\tmux -V | cut -d" " -f2` -lt 2.1 ]]; then
		tmux set -g mode-mouse on
		tmux set -g mouse-resize-pane on
		tmux set -g mouse-select-pane on
		tmux set -g mouse-select-window on
		clear
	else
		tmux set -g mouse on
		clear
	fi
fi

to_trash() {
	for file in $@
	do
		mv $file ~/.trash
	done
}
alias rm="to_trash"
alias tgvim="gvim --remote-tab"
alias tvim="gvim --remote-tab"

