name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v4
    - name: Restore cached repositories
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          build/neovim
          build/tig
          build/tmux
          build/vim
        key: ${{ runner.os }}-repos
    - name: Test install.sh install (/wo nvim)
      run: ./install-invoke.sh
    - name: Test install.sh buildtools
      shell: zsh -le {0}
      run: ./install-invoke.sh buildtools
    - name: Save cache
      id: cache-save
      uses: actions/cache/save@v4
      with:
        path: |
          build/neovim
          build/tig
          build/tmux
          build/vim
        key: ${{ steps.cache-restore.outputs.cache-primary-key }}
    - name: Test install.sh install (/w nvim)
      shell: zsh -le {0}
      run: ./install-invoke.sh
    - name: Test install.sh runtest
      shell: zsh -le {0}
      run: ./install-invoke.sh runtest
