name: Test install.sh on Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test install.sh buildtools
      shell: C:\Program Files\Git\bin\bash.exe
      run: "./install.sh"
