name: Test install on Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Test install.sh install
      shell: cmd
      run: '"C:\Program Files\Git\bin\bash.exe" -c "./install-invoke.sh"'
    - name: Test install.sh runtest
      shell: cmd
      run: 'set VADER_OUTPUT_FILE=test_result.log && vim --not-a-term --cmd "let g:is_test = 1" --cmd "set shortmess=a cmdheight=10" -c "Vader! "./vim/test/myvimrc.vader"" & type test_result.log'
