name: Test buildtools on Mac OS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: macos-11
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Test install.sh buildtools
      run: ./install-invoke.sh buildtools
    - name: Test install.sh install
      run: ./install-invoke.sh
    - name: Test install.sh runtest
      run: ./install-invoke.sh runtest
