name: Test install on Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test install.sh buildtools
      shell: cmd
      run: '"C:\Program Files\Git\bin\bash.exe" -c "./install-invoke.sh"'
    - name: Test :PlugInstall
      shell: cmd
      run: 'vim --not-a-term --cmd "let g:is_test = 1" --cmd "set shortmess=a cmdheight=10" -c ":PlugInstall --sync" -c ":qa!"'
