name: Test install on Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Test install.sh install
      shell: cmd
      run: '"C:\Program Files\Git\bin\bash.exe" -c "./install-invoke.sh"'
    - name: Test install.sh update
      shell: cmd
      run: '"C:\Program Files\Git\bin\bash.exe" -c "./install-invoke.sh update"'
    - name: Test install.sh runtest
      shell: cmd
      run: '"C:\Program Files\Git\bin\bash.exe" -c "./install-invoke.sh runtest"'
