name: Test buildtools on Ubuntu 20.04

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Test install.sh buildtools
      run: ./install-invoke.sh buildtools && ./install-invoke.sh && ./install-invoke.sh update && ./install-invoke.sh runtest
