name: Test buildtools on Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v4
    - name: Restore cached repositories
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          build/neovim
          build/tig
          build/tmux
          build/vim
        key: ${{ runner.os }}-repos
    - name: Test install.sh buildtools
      run: ./install-invoke.sh buildtools
    - name: Test install.sh install
      run: ./install-invoke.sh
    - name: Test install.sh runtest
      run: ./install-invoke.sh runtest
