name: Test buildtools on Mac OS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Test install.sh buildtools
      run: ./install-invoke.sh buildtools && ./install-invoke.sh && ./install-invoke.sh runtest
