name: Test install on Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v4
    - name: Restore cached repositories
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          build/neovim
          build/tig
          build/tmux
          build/vim
        key: ${{ runner.os }}-repos
    - name: Install vim with chocolatey
      shell: cmd
      run: 'choco install vim deno neovim lua luarocks --force'
    - name: Test install.sh install
      shell: cmd
      run: '"C:\Program Files\Git\bin\bash.exe" -c "./install-invoke.sh"'
    - name: Test runtest.bat
      shell: cmd
      run: 'runtest.bat'
    - name: Save cache
      id: cache-save
      uses: actions/cache/save@v4
      with:
        path: |
          build/neovim
          build/tig
          build/tmux
          build/vim
        key: ${{ steps.cache-restore.outputs.cache-primary-key }}
